---

k3s_version: v1.34.1+k3s1

k3s_node_name: ""
k3s_node_role: server
k3s_node_leader: false
k3s_node_config: {}

k3s_service_name: k3s

k3s_cluster_cidr: 10.33.0.0/16
k3s_service_cidr: 10.34.0.0/16
