---

- include_vars: "{{ k3s_node_role | lower }}.yaml"
- include_tasks: facts.yaml

- name: configure k3s
  block:
    - ansible.builtin.file:
        path: /etc/rancher/k3s
        state: directory
    - ansible.builtin.copy:
        dest: /etc/rancher/k3s/config.yaml
        content: "{{ k3s_node_config | to_nice_yaml() }}"
  tags:
    - k3s
    - k3s-setup

- name: install k3s
  when: k3s_current_version | length == 0
  become: true
  block:
    - name: get k3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh
        mode: 0755
    - name: run k3s install script
      ansible.builtin.shell: |
        INSTALL_K3S_SKIP_START=true \
        INSTALL_K3S_VERSION={{ k3s_version }} \
        \
        sh /tmp/k3s-install.sh \
          {{ k3s_node_role | lower }}
    - name: delete k3s install script
      ansible.builtin.file:
        path: /tmp/k3s-install.sh
        state: absent
  notify:
    - start k3s service
  tags:
    - k3s
    - k3s-setup

- name: get the server token
  when: k3s_node_leader
  block:
    - name: wait for token
      ansible.builtin.wait_for:
        path: /var/lib/rancher/k3s/server/token
    - name: read node-token from master
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/token
      register: k3s_server_node_token
    - name: store master node-token
      ansible.builtin.set_fact:
        token: "{{ k3s_server_node_token.content | b64decode | regex_replace('\n', '') }}"
  tags:
    - k3s
    - k3s-setup

