---

- name: update apt packages to the latest version
  apt:
    update_cache: yes
    upgrade: full
  become: true
  tags:
    - pi5
    - pi5-update

- include_tasks: ./cmdline.yaml
  vars:
    key: cgroup_enable
    value: memory
    update: false
  tags:
  - pi5
  - pi5-cmdline

- include_tasks: ./cmdline.yaml
  vars:
    key: cgroup_memory
    value: 1
    update: true
  tags:
  - pi5
  - pi5-cmdline
