services:

  ansible:
    build:
      context: .
    volumes:
      - ./:/workspace
      - ./ansible.cfg:/etc/ansible/ansible.cfg
      - "~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock:/tmp/ssh-agent.sock"
    environment:
      SSH_AUTH_SOCK: /tmp/ssh-agent.sock
      OP_SERVICE_ACCOUNT_TOKEN: ${OP_SERVICE_ACCOUNT_TOKEN}
    working_dir: /workspace
