---

- name: wireguard client provisioning
  hosts: external
  roles:
    - wireguard
  become: true
  gather_facts: true
  tags:
    - wireguard

- name: k3s cluster provisioning
  hosts: cluster
  roles:
    - k3s
  serial:
    - 1
    - "100%"
  become: true
  gather_facts: true
  tags:
    - k3s
