# rnk -- RackNerd KVM Hosts
rnk:
  hosts:
    rnk-01:
      ansible_host: 167.160.190.221
  vars:
    ansible_user: root
    # wireguard vars
    wireguard_private_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      30633039373365666432333336306239663137383862666333653038326234303162376637323930
      3330323831616263336530653538323665353766636437640a643132346136356433613866313164
      61393566663937343638623063306662393839663862313031386333663562343862363633353763
      3230653262323830370a343962323330666638343935623666626435313765626565303961643833
      34366236343036616633666362333333356165386232636133353761613065366230646565346463
      3964633934306330656138303638383131633039626566393436
    wireguard_peer_endpoint: vpn.kurtainerd.io:51820
    wireguard_peer_public_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      61313239653561623431623931616438373036366465616565346639656231653330303637666262
      6239656165303663316634353530633930653337616439320a303866313131666330623862336332
      30636433383939386236646438346331356235613765646532663761396137323239393835653766
      6332323064653530350a383930613065336438646430393839323331636465633663633565303965
      65303065643061383337666565353333336632666265313361336562373636663831663838633431
      6465303631623230306333623838663762623765613934343462
    wireguard_peer_preshared_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      35386663633763313335643836626536353763383635653931623933353239663562643061643238
      3636616230393937396332363137356139616437323761380a353738653332626165323763623630
      66613364376666623266353034616161663266353039616330653261666561636662343133636235
      6437613065623361390a363633353962313438663463626636626461356131333265353434643538
      35396665333431333433646335386538323862656535313630306465363961366463643234633235
      6263336131343939626335323739623438343836623433346364

external:
  hosts:
    rnk-01: {}
